// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjiAKASzPQLVOA2z_4v7cpyipSB5f1d4o',
    appId: '1:412666771363:web:e5b4cd10218d0600218c16',
    messagingSenderId: '412666771363',
    projectId: 'f2-bea85',
    authDomain: 'f2-bea85.firebaseapp.com',
    storageBucket: 'f2-bea85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCll_y0My0f-Av58-7hd9vqjm0hL-MJbO4',
    appId: '1:412666771363:android:6f8f08b1727d555d218c16',
    messagingSenderId: '412666771363',
    projectId: 'f2-bea85',
    storageBucket: 'f2-bea85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmLD8enq4f2U-LbwhLSz9dohtpo7lrt9o',
    appId: '1:412666771363:ios:f3c8b7e2e490fe64218c16',
    messagingSenderId: '412666771363',
    projectId: 'f2-bea85',
    storageBucket: 'f2-bea85.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
